name: Development CI/CD
on:
    push:
        branches:
            - dev
    pull_request:
        branches:
            - dev

jobs:
    laravel-tests:
        name: CI - PHP Tests
        runs-on: ubuntu-latest
        steps:
            -   name: Get Code
                uses: actions/checkout@v3
            -   name: Install Composer
                uses: shivammathur/setup-php@v2
                with:
                    php-version: '8.2'
                    coverage: none
            -   name: Install Composer Dependencies
                run: composer install -n --prefer-dist
            -   name: Prepare Laravel Application
                run: |
                    cp .env.example .env
                    php artisan key:generate
            -   name: Run Tests
                run: php artisan test

    react-tests:
        name: CI - NodeJS Tests
        runs-on: ubuntu-latest
        steps:
            -   name: Get Code
                uses: actions/checkout@v3
            -   name: Install NodeJS
                uses: actions/setup-node@v3
                with:
                    node-version: 18
            -   name: Install NodeJS Dependencies
                run: npm ci
            -   name: Build NodeJS
                run: npm run build
            -   name: Test NodeJS
                run: npm test
                    
                
